### ISSUE TITLE
TokuDB?

### ISSUE THREAD

**Issue by errm** [docker-library/percona#10]
Hi I have been experimenting with enabling the TokuDB engine in Percona Server . . . Results here https://github.com/reevoo/percona-tokudb, if it is something you might be interesting in merging I can open a proper PR?

It might be best as something on another tag, or with an env var to enable it?

**Comment by denji** [comment]
Env: `INIT_TOKUDB=yes` — https://github.com/percona/percona-docker/blob/master/percona-server/ps-entry.sh#L10-L51

```
if test -f /sys/kernel/mm/transparent_hugepage/khugepaged/defrag; then
  echo 0 > /sys/kernel/mm/transparent_hugepage/khugepaged/defrag
fi
if test -f /sys/kernel/mm/transparent_hugepage/defrag; then
  echo never > /sys/kernel/mm/transparent_hugepage/defrag
fi
if test -f /sys/kernel/mm/transparent_hugepage/enabled; then
  echo never > /sys/kernel/mm/transparent_hugepage/enabled
fi
```

**Comment by yosifkit** [comment]
Not sure if you need percona, but TokuDB is already available in the MariaDB image:

``` console
$ docker run -d --name maria -e MYSQL_ROOT_PASSWORD=12345 mariadb --plugin-load=ha_tokudb --plugin-dir=/usr/lib/mysql/plugin --default-storage-engine=tokudb
```

Seeing that it is automatically there, it wouldn't be too much of a stretch to install it in the percona image. We just need to add `percona-server-tokudb-${PERCONA_MAJOR}` to the apt-get install.  It should only add about `12.1 MB` of additional files to the image.

``` console
$ # after installing percona-server-tokudb
$ docker run -d --name percona-toku -e MYSQL_ROOT_PASSWORD=12345 -e LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1 percona --plugin-load=ha_tokudb.so --plugin-dir=/usr/lib/mysql/plugin/ --default-storage-engine=tokudb
```

It might make sense to just set `LD_PRELOAD` in an `ENV` in the Dockerfile, but I am not sure if that would affect users who don't turn on tokudb.  That way mariadb and percona would be the same to enable tokudb (aside from percona requiring a `.so`).

I don't see the need for an env to enable it, since it can just be passed as flags to the mysql daemon or a could be put in a custom conf file in `/etc/mysql/conf.d/`.

**Comment by wglambert** [comment]
Given that the question/request seems resolved and a few years without comment I'm going to close.

If you believe this to be in error then let me know and I'll re-open it
