### ISSUE TITLE
Restarting mysql causes docker container to exit

### ISSUE THREAD

**Issue by klimis** [docker-library/percona#22]
Started container with `docker run -v /tmp/:/tmp --name percona -p 3344:3306 -e MYSQL_ROOT_PASSWORD=123 -d percona:5.7`

and then `docker exec -i -t percona bash`

once inside the container every time i try to restart or to stop mysql `/etc/init.d/mysql stop`  causes docker container to stop and exit

**Comment by yosifkit** [comment]
That is the expected behavior of the container because there is no init system running within the container; `mysqld` is pid 1.

The initd script is killing pid 1 of the container and the kernel kills the rest of the container (and thus the init script itself is killed by the kernel before the script can continue).  To manage mysql lifecycle, use `docker start`, `docker stop`, or `docker restart`.  You could also use `docker kill` to send a specific signal as needed.
