### ISSUE TITLE
ARM64 Support

### ISSUE THREAD

**Issue by lag-linaro** [docker-library/percona#62]
Any chance we can have support for ARM64 enabled?

It looks as if the Dockerfile currently pulls in pre-built packages from the Percona repos.

For ARM64, perhaps we can build from source, or pull from another repo?

**Comment by wglambert** [comment]
It doesn't appear Percona supports ARM64 
https://www.percona.com/doc/percona-server/LATEST/installation/apt_repo.html

> Supported Platforms:
> 
> x86
> x86_64 (also known as amd64)

**Comment by lag-linaro** [comment]
Yes, I saw that.  It's certainly a shame.  They also do not have ARM64 support on their roadmap.

It is possible to [BUILD FROM SOURCE](https://www.percona.com/doc/percona-server/5.7/installation.html#installing-percona-server-from-a-source-tarball) however, something we can do when users request a `docker pull` from an ARM64 machine.

I am also more than happy to do the leg work to make this happen.  Given that a PR of this nature would be considered.

**Comment by wglambert** [comment]
Here's previous comments on similar issues 
https://github.com/docker-library/mysql/issues/318#issuecomment-339460074 
https://github.com/docker-library/mariadb/issues/125#issuecomment-325746076

**Comment by mmarmm** [comment]
@wglambert FYI - MariaDB now has DOI support for Arm64: https://github.com/docker-library/mariadb/pull/184#issuecomment-406779840 . It's also likely MySQL will also provide Arm64 support in the next several weeks given the betas. What's the likelihood of using distro packaging vs. upstream to enable multi-arch support? Thanks.

**Comment by mmarmm** [comment]
Both issues mentioned above are now [being] resolved: MariaDB has Arm64 support [0] and MySQL is adding support for arm64 [1-4]. It would appear that Percona support 8.0 is not in place yet and we have to wait for that at least and then see if if repo.percona.com will support arm64, otherwise decide to build from source or pull from a distro vs. pulling from the repo. Please let us know if there's anything we can do to help this Percona image keep up with the others.

[0] https://hub.docker.com/r/arm64v8/mariadb/
[1] http://repo.mysql.com/yum/mysql-8.0-community/docker/aarch64/mysql-community-server-minimal-8.0.12-1.el7.aarch64.rpm
[2] https://dev.mysql.com/doc/refman/8.0/en/linux-installation-yum-repo.html#yum-install-platform-specifics
[3] https://github.com/docker-library/mysql/issues/318#issuecomment-414299891
[4] https://github.com/ltangvald/mysql-1/blob/mysql-server-arm/8.0-aarch64/Dockerfile

**Comment by tianon** [comment]
I agree that Percona probably _should_ consider supporting ARM64, but that's a conversation that needs to be had with Percona -- we simply maintain an image for their software and are not affiliated with them directly (nor do we have contacts there).

It's also worth noting that we've been considering deprecating this image entirely in favor of [the images that Percona maintains directly themselves](https://hub.docker.com/r/percona/).

Closing, given that there's nothing more we (the official images maintainers) can do here.
